#include "goldilocks_cubic_extension.hpp"
#include "zhInv.hpp"
#include "starks.hpp"
#include "constant_pols_starks.hpp"
#include "allSteps.hpp"

void AllSteps::step3_first(StepsParams &params, uint64_t i) {
     Goldilocks::Element tmp_76;
     Goldilocks::copy(tmp_76, params.pols[12 + i*16]);
     Goldilocks::Element tmp_77;
     Goldilocks::copy(tmp_77, tmp_76);
     Goldilocks::Element tmp_78;
     Goldilocks::copy(tmp_78, params.pols[13 + ((i + 1)%1024)*16]);
     Goldilocks::Element tmp_79;
     Goldilocks::copy(tmp_79, tmp_78);
     Goldilocks::Element tmp_80;
     Goldilocks::mul(tmp_80, params.pols[12 + i*16], params.pols[13 + ((i + 1)%1024)*16]);
     Goldilocks::Element tmp_81;
     Goldilocks::copy(tmp_81, tmp_80);
     Goldilocks::Element tmp_82;
     Goldilocks::copy(tmp_82,  params.pConstPols->getElement(7,i));
     Goldilocks::Element tmp_83;
     Goldilocks::copy(tmp_83, tmp_82);
     Goldilocks::Element tmp_84;
     Goldilocks::copy(tmp_84,  params.pConstPols->getElement(8,i));
     Goldilocks::Element tmp_85;
     Goldilocks::copy(tmp_85, tmp_84);
     Goldilocks::Element tmp_86;
     Goldilocks::copy(tmp_86, params.pols[14 + i*16]);
     Goldilocks::Element tmp_87;
     Goldilocks::copy(tmp_87, tmp_86);
     Goldilocks::copy(params.pols[44039 + i*17],  params.pConstPols->getElement(6,i));
     Goldilocks3::Element tmp_44;
     Goldilocks3::mul(tmp_44, tmp_83, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_45;
     Goldilocks3::add(tmp_45, tmp_85, tmp_44);
     Goldilocks3::Element tmp_46;
     Goldilocks3::mul(tmp_46, tmp_45, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_47;
     Goldilocks3::add(tmp_47, tmp_87, tmp_46);
     Goldilocks3::Element tmp_48;
     Goldilocks3::sub(tmp_48, tmp_47, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_49;
     Goldilocks3::mul(tmp_49, params.pols[44039 + i*17], tmp_48);
     Goldilocks3::Element tmp_88;
     Goldilocks3::add(tmp_88, tmp_49, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::copy(params.pols[44035 + i*17], params.pols[11 + i*16]);
     Goldilocks3::Element tmp_50;
     Goldilocks3::mul(tmp_50, tmp_77, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_51;
     Goldilocks3::add(tmp_51, tmp_79, tmp_50);
     Goldilocks3::Element tmp_52;
     Goldilocks3::mul(tmp_52, tmp_51, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_53;
     Goldilocks3::add(tmp_53, tmp_81, tmp_52);
     Goldilocks3::Element tmp_54;
     Goldilocks3::sub(tmp_54, tmp_53, tmp_88);
     Goldilocks3::Element tmp_55;
     Goldilocks3::mul(tmp_55, params.pols[44035 + i*17], tmp_54);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[16393 + i*21]), tmp_55, tmp_88);
     Goldilocks3::Element tmp_56;
     Goldilocks3::add(tmp_56, (Goldilocks3::Element &)(params.pols[16393 + i*21]), (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_57;
     Goldilocks3::add(tmp_57, tmp_88, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16396 + i*21]), tmp_56, tmp_57);
     Goldilocks::Element tmp_89;
     Goldilocks::copy(tmp_89, params.pols[2 + i*16]);
     Goldilocks3::Element tmp_58;
     Goldilocks3::mul(tmp_58, (Goldilocks::Element &)*params.x_n[i], (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_59;
     Goldilocks3::add(tmp_59, tmp_89, tmp_58);
     Goldilocks3::Element tmp_90;
     Goldilocks3::add(tmp_90, tmp_59, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_91;
     Goldilocks::copy(tmp_91, params.pols[3 + i*16]);
     Goldilocks3::Element tmp_60;
     Goldilocks3::mul(tmp_60, Goldilocks::fromU64(12275445934081160404ULL), (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_61;
     Goldilocks3::mul(tmp_61, (Goldilocks::Element &)*params.x_n[i], tmp_60);
     Goldilocks3::Element tmp_62;
     Goldilocks3::add(tmp_62, tmp_91, tmp_61);
     Goldilocks3::Element tmp_63;
     Goldilocks3::add(tmp_63, tmp_62, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_92;
     Goldilocks3::mul(tmp_92, tmp_90, tmp_63);
     Goldilocks::Element tmp_93;
     Goldilocks::copy(tmp_93, params.pols[4 + i*16]);
     Goldilocks3::Element tmp_64;
     Goldilocks3::mul(tmp_64, Goldilocks::fromU64(4756475762779100925ULL), (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_65;
     Goldilocks3::mul(tmp_65, (Goldilocks::Element &)*params.x_n[i], tmp_64);
     Goldilocks3::Element tmp_66;
     Goldilocks3::add(tmp_66, tmp_93, tmp_65);
     Goldilocks3::Element tmp_67;
     Goldilocks3::add(tmp_67, tmp_66, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16399 + i*21]), tmp_92, tmp_67);
     Goldilocks::Element tmp_94;
     Goldilocks::copy(tmp_94,  params.pConstPols->getElement(3,i));
     Goldilocks3::Element tmp_68;
     Goldilocks3::mul(tmp_68, tmp_94, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_69;
     Goldilocks3::add(tmp_69, tmp_89, tmp_68);
     Goldilocks3::Element tmp_95;
     Goldilocks3::add(tmp_95, tmp_69, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_96;
     Goldilocks::copy(tmp_96,  params.pConstPols->getElement(4,i));
     Goldilocks3::Element tmp_70;
     Goldilocks3::mul(tmp_70, tmp_96, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_71;
     Goldilocks3::add(tmp_71, tmp_91, tmp_70);
     Goldilocks3::Element tmp_72;
     Goldilocks3::add(tmp_72, tmp_71, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_97;
     Goldilocks3::mul(tmp_97, tmp_95, tmp_72);
     Goldilocks::Element tmp_98;
     Goldilocks::copy(tmp_98,  params.pConstPols->getElement(5,i));
     Goldilocks3::Element tmp_73;
     Goldilocks3::mul(tmp_73, tmp_98, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_74;
     Goldilocks3::add(tmp_74, tmp_93, tmp_73);
     Goldilocks3::Element tmp_75;
     Goldilocks3::add(tmp_75, tmp_74, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16402 + i*21]), tmp_97, tmp_75);
}

void AllSteps::step3_i(StepsParams &params, uint64_t i) {
     Goldilocks::Element tmp_76;
     Goldilocks::copy(tmp_76, params.pols[12 + i*16]);
     Goldilocks::Element tmp_77;
     Goldilocks::copy(tmp_77, tmp_76);
     Goldilocks::Element tmp_78;
     Goldilocks::copy(tmp_78, params.pols[13 + ((i + 1)%1024)*16]);
     Goldilocks::Element tmp_79;
     Goldilocks::copy(tmp_79, tmp_78);
     Goldilocks::Element tmp_80;
     Goldilocks::mul(tmp_80, params.pols[12 + i*16], params.pols[13 + ((i + 1)%1024)*16]);
     Goldilocks::Element tmp_81;
     Goldilocks::copy(tmp_81, tmp_80);
     Goldilocks::Element tmp_82;
     Goldilocks::copy(tmp_82,  params.pConstPols->getElement(7,i));
     Goldilocks::Element tmp_83;
     Goldilocks::copy(tmp_83, tmp_82);
     Goldilocks::Element tmp_84;
     Goldilocks::copy(tmp_84,  params.pConstPols->getElement(8,i));
     Goldilocks::Element tmp_85;
     Goldilocks::copy(tmp_85, tmp_84);
     Goldilocks::Element tmp_86;
     Goldilocks::copy(tmp_86, params.pols[14 + i*16]);
     Goldilocks::Element tmp_87;
     Goldilocks::copy(tmp_87, tmp_86);
     Goldilocks::copy(params.pols[44039 + i*17],  params.pConstPols->getElement(6,i));
     Goldilocks3::Element tmp_44;
     Goldilocks3::mul(tmp_44, tmp_83, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_45;
     Goldilocks3::add(tmp_45, tmp_85, tmp_44);
     Goldilocks3::Element tmp_46;
     Goldilocks3::mul(tmp_46, tmp_45, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_47;
     Goldilocks3::add(tmp_47, tmp_87, tmp_46);
     Goldilocks3::Element tmp_48;
     Goldilocks3::sub(tmp_48, tmp_47, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_49;
     Goldilocks3::mul(tmp_49, params.pols[44039 + i*17], tmp_48);
     Goldilocks3::Element tmp_88;
     Goldilocks3::add(tmp_88, tmp_49, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::copy(params.pols[44035 + i*17], params.pols[11 + i*16]);
     Goldilocks3::Element tmp_50;
     Goldilocks3::mul(tmp_50, tmp_77, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_51;
     Goldilocks3::add(tmp_51, tmp_79, tmp_50);
     Goldilocks3::Element tmp_52;
     Goldilocks3::mul(tmp_52, tmp_51, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_53;
     Goldilocks3::add(tmp_53, tmp_81, tmp_52);
     Goldilocks3::Element tmp_54;
     Goldilocks3::sub(tmp_54, tmp_53, tmp_88);
     Goldilocks3::Element tmp_55;
     Goldilocks3::mul(tmp_55, params.pols[44035 + i*17], tmp_54);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[16393 + i*21]), tmp_55, tmp_88);
     Goldilocks3::Element tmp_56;
     Goldilocks3::add(tmp_56, (Goldilocks3::Element &)(params.pols[16393 + i*21]), (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_57;
     Goldilocks3::add(tmp_57, tmp_88, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16396 + i*21]), tmp_56, tmp_57);
     Goldilocks::Element tmp_89;
     Goldilocks::copy(tmp_89, params.pols[2 + i*16]);
     Goldilocks3::Element tmp_58;
     Goldilocks3::mul(tmp_58, (Goldilocks::Element &)*params.x_n[i], (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_59;
     Goldilocks3::add(tmp_59, tmp_89, tmp_58);
     Goldilocks3::Element tmp_90;
     Goldilocks3::add(tmp_90, tmp_59, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_91;
     Goldilocks::copy(tmp_91, params.pols[3 + i*16]);
     Goldilocks3::Element tmp_60;
     Goldilocks3::mul(tmp_60, Goldilocks::fromU64(12275445934081160404ULL), (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_61;
     Goldilocks3::mul(tmp_61, (Goldilocks::Element &)*params.x_n[i], tmp_60);
     Goldilocks3::Element tmp_62;
     Goldilocks3::add(tmp_62, tmp_91, tmp_61);
     Goldilocks3::Element tmp_63;
     Goldilocks3::add(tmp_63, tmp_62, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_92;
     Goldilocks3::mul(tmp_92, tmp_90, tmp_63);
     Goldilocks::Element tmp_93;
     Goldilocks::copy(tmp_93, params.pols[4 + i*16]);
     Goldilocks3::Element tmp_64;
     Goldilocks3::mul(tmp_64, Goldilocks::fromU64(4756475762779100925ULL), (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_65;
     Goldilocks3::mul(tmp_65, (Goldilocks::Element &)*params.x_n[i], tmp_64);
     Goldilocks3::Element tmp_66;
     Goldilocks3::add(tmp_66, tmp_93, tmp_65);
     Goldilocks3::Element tmp_67;
     Goldilocks3::add(tmp_67, tmp_66, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16399 + i*21]), tmp_92, tmp_67);
     Goldilocks::Element tmp_94;
     Goldilocks::copy(tmp_94,  params.pConstPols->getElement(3,i));
     Goldilocks3::Element tmp_68;
     Goldilocks3::mul(tmp_68, tmp_94, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_69;
     Goldilocks3::add(tmp_69, tmp_89, tmp_68);
     Goldilocks3::Element tmp_95;
     Goldilocks3::add(tmp_95, tmp_69, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_96;
     Goldilocks::copy(tmp_96,  params.pConstPols->getElement(4,i));
     Goldilocks3::Element tmp_70;
     Goldilocks3::mul(tmp_70, tmp_96, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_71;
     Goldilocks3::add(tmp_71, tmp_91, tmp_70);
     Goldilocks3::Element tmp_72;
     Goldilocks3::add(tmp_72, tmp_71, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_97;
     Goldilocks3::mul(tmp_97, tmp_95, tmp_72);
     Goldilocks::Element tmp_98;
     Goldilocks::copy(tmp_98,  params.pConstPols->getElement(5,i));
     Goldilocks3::Element tmp_73;
     Goldilocks3::mul(tmp_73, tmp_98, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_74;
     Goldilocks3::add(tmp_74, tmp_93, tmp_73);
     Goldilocks3::Element tmp_75;
     Goldilocks3::add(tmp_75, tmp_74, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16402 + i*21]), tmp_97, tmp_75);
}

void AllSteps::step3_last(StepsParams &params, uint64_t i) {
     Goldilocks::Element tmp_76;
     Goldilocks::copy(tmp_76, params.pols[12 + i*16]);
     Goldilocks::Element tmp_77;
     Goldilocks::copy(tmp_77, tmp_76);
     Goldilocks::Element tmp_78;
     Goldilocks::copy(tmp_78, params.pols[13 + ((i + 1)%1024)*16]);
     Goldilocks::Element tmp_79;
     Goldilocks::copy(tmp_79, tmp_78);
     Goldilocks::Element tmp_80;
     Goldilocks::mul(tmp_80, params.pols[12 + i*16], params.pols[13 + ((i + 1)%1024)*16]);
     Goldilocks::Element tmp_81;
     Goldilocks::copy(tmp_81, tmp_80);
     Goldilocks::Element tmp_82;
     Goldilocks::copy(tmp_82,  params.pConstPols->getElement(7,i));
     Goldilocks::Element tmp_83;
     Goldilocks::copy(tmp_83, tmp_82);
     Goldilocks::Element tmp_84;
     Goldilocks::copy(tmp_84,  params.pConstPols->getElement(8,i));
     Goldilocks::Element tmp_85;
     Goldilocks::copy(tmp_85, tmp_84);
     Goldilocks::Element tmp_86;
     Goldilocks::copy(tmp_86, params.pols[14 + i*16]);
     Goldilocks::Element tmp_87;
     Goldilocks::copy(tmp_87, tmp_86);
     Goldilocks::copy(params.pols[44039 + i*17],  params.pConstPols->getElement(6,i));
     Goldilocks3::Element tmp_44;
     Goldilocks3::mul(tmp_44, tmp_83, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_45;
     Goldilocks3::add(tmp_45, tmp_85, tmp_44);
     Goldilocks3::Element tmp_46;
     Goldilocks3::mul(tmp_46, tmp_45, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_47;
     Goldilocks3::add(tmp_47, tmp_87, tmp_46);
     Goldilocks3::Element tmp_48;
     Goldilocks3::sub(tmp_48, tmp_47, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_49;
     Goldilocks3::mul(tmp_49, params.pols[44039 + i*17], tmp_48);
     Goldilocks3::Element tmp_88;
     Goldilocks3::add(tmp_88, tmp_49, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::copy(params.pols[44035 + i*17], params.pols[11 + i*16]);
     Goldilocks3::Element tmp_50;
     Goldilocks3::mul(tmp_50, tmp_77, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_51;
     Goldilocks3::add(tmp_51, tmp_79, tmp_50);
     Goldilocks3::Element tmp_52;
     Goldilocks3::mul(tmp_52, tmp_51, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_53;
     Goldilocks3::add(tmp_53, tmp_81, tmp_52);
     Goldilocks3::Element tmp_54;
     Goldilocks3::sub(tmp_54, tmp_53, tmp_88);
     Goldilocks3::Element tmp_55;
     Goldilocks3::mul(tmp_55, params.pols[44035 + i*17], tmp_54);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[16393 + i*21]), tmp_55, tmp_88);
     Goldilocks3::Element tmp_56;
     Goldilocks3::add(tmp_56, (Goldilocks3::Element &)(params.pols[16393 + i*21]), (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_57;
     Goldilocks3::add(tmp_57, tmp_88, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16396 + i*21]), tmp_56, tmp_57);
     Goldilocks::Element tmp_89;
     Goldilocks::copy(tmp_89, params.pols[2 + i*16]);
     Goldilocks3::Element tmp_58;
     Goldilocks3::mul(tmp_58, (Goldilocks::Element &)*params.x_n[i], (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_59;
     Goldilocks3::add(tmp_59, tmp_89, tmp_58);
     Goldilocks3::Element tmp_90;
     Goldilocks3::add(tmp_90, tmp_59, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_91;
     Goldilocks::copy(tmp_91, params.pols[3 + i*16]);
     Goldilocks3::Element tmp_60;
     Goldilocks3::mul(tmp_60, Goldilocks::fromU64(12275445934081160404ULL), (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_61;
     Goldilocks3::mul(tmp_61, (Goldilocks::Element &)*params.x_n[i], tmp_60);
     Goldilocks3::Element tmp_62;
     Goldilocks3::add(tmp_62, tmp_91, tmp_61);
     Goldilocks3::Element tmp_63;
     Goldilocks3::add(tmp_63, tmp_62, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_92;
     Goldilocks3::mul(tmp_92, tmp_90, tmp_63);
     Goldilocks::Element tmp_93;
     Goldilocks::copy(tmp_93, params.pols[4 + i*16]);
     Goldilocks3::Element tmp_64;
     Goldilocks3::mul(tmp_64, Goldilocks::fromU64(4756475762779100925ULL), (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_65;
     Goldilocks3::mul(tmp_65, (Goldilocks::Element &)*params.x_n[i], tmp_64);
     Goldilocks3::Element tmp_66;
     Goldilocks3::add(tmp_66, tmp_93, tmp_65);
     Goldilocks3::Element tmp_67;
     Goldilocks3::add(tmp_67, tmp_66, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16399 + i*21]), tmp_92, tmp_67);
     Goldilocks::Element tmp_94;
     Goldilocks::copy(tmp_94,  params.pConstPols->getElement(3,i));
     Goldilocks3::Element tmp_68;
     Goldilocks3::mul(tmp_68, tmp_94, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_69;
     Goldilocks3::add(tmp_69, tmp_89, tmp_68);
     Goldilocks3::Element tmp_95;
     Goldilocks3::add(tmp_95, tmp_69, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_96;
     Goldilocks::copy(tmp_96,  params.pConstPols->getElement(4,i));
     Goldilocks3::Element tmp_70;
     Goldilocks3::mul(tmp_70, tmp_96, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_71;
     Goldilocks3::add(tmp_71, tmp_91, tmp_70);
     Goldilocks3::Element tmp_72;
     Goldilocks3::add(tmp_72, tmp_71, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_97;
     Goldilocks3::mul(tmp_97, tmp_95, tmp_72);
     Goldilocks::Element tmp_98;
     Goldilocks::copy(tmp_98,  params.pConstPols->getElement(5,i));
     Goldilocks3::Element tmp_73;
     Goldilocks3::mul(tmp_73, tmp_98, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_74;
     Goldilocks3::add(tmp_74, tmp_93, tmp_73);
     Goldilocks3::Element tmp_75;
     Goldilocks3::add(tmp_75, tmp_74, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16402 + i*21]), tmp_97, tmp_75);
}
