#include "goldilocks_cubic_extension.hpp"
#include "zhInv.hpp"
#include "starks.hpp"
#include "constant_pols_starks.hpp"
#include "allSteps.hpp"

void AllSteps::step3prev_first(StepsParams &params, uint64_t i) {
     Goldilocks::Element tmp_44;
     Goldilocks::copy(tmp_44,  params.pConstPols->getElement(7,i));
     Goldilocks::Element tmp_45;
     Goldilocks::copy(tmp_45, tmp_44);
     Goldilocks::Element tmp_46;
     Goldilocks::copy(tmp_46,  params.pConstPols->getElement(8,i));
     Goldilocks::Element tmp_47;
     Goldilocks::copy(tmp_47, tmp_46);
     Goldilocks::Element tmp_48;
     Goldilocks::copy(tmp_48, params.pols[14 + i*16]);
     Goldilocks::Element tmp_49;
     Goldilocks::copy(tmp_49, tmp_48);
     Goldilocks::copy(params.pols[44039 + i*17],  params.pConstPols->getElement(6,i));
     Goldilocks3::Element tmp_0;
     Goldilocks3::mul(tmp_0, tmp_45, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_1;
     Goldilocks3::add(tmp_1, tmp_47, tmp_0);
     Goldilocks3::Element tmp_2;
     Goldilocks3::mul(tmp_2, tmp_1, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_3;
     Goldilocks3::add(tmp_3, tmp_49, tmp_2);
     Goldilocks3::Element tmp_4;
     Goldilocks3::sub(tmp_4, tmp_3, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_5;
     Goldilocks3::mul(tmp_5, params.pols[44039 + i*17], tmp_4);
     Goldilocks3::Element tmp_50;
     Goldilocks3::add(tmp_50, tmp_5, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::copy(params.pols[44035 + i*17], params.pols[11 + i*16]);
     Goldilocks::Element tmp_51;
     Goldilocks::copy(tmp_51, params.pols[12 + i*16]);
     Goldilocks::Element tmp_52;
     Goldilocks::copy(tmp_52, tmp_51);
     Goldilocks::Element tmp_53;
     Goldilocks::copy(tmp_53, params.pols[13 + ((i + 1)%1024)*16]);
     Goldilocks::Element tmp_54;
     Goldilocks::copy(tmp_54, tmp_53);
     Goldilocks::Element tmp_55;
     Goldilocks::mul(tmp_55, params.pols[12 + i*16], params.pols[13 + ((i + 1)%1024)*16]);
     Goldilocks::Element tmp_56;
     Goldilocks::copy(tmp_56, tmp_55);
     Goldilocks3::Element tmp_6;
     Goldilocks3::mul(tmp_6, tmp_52, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_7;
     Goldilocks3::add(tmp_7, tmp_54, tmp_6);
     Goldilocks3::Element tmp_8;
     Goldilocks3::mul(tmp_8, tmp_7, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_9;
     Goldilocks3::add(tmp_9, tmp_56, tmp_8);
     Goldilocks3::Element tmp_10;
     Goldilocks3::sub(tmp_10, tmp_9, tmp_50);
     Goldilocks3::Element tmp_11;
     Goldilocks3::mul(tmp_11, params.pols[44035 + i*17], tmp_10);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[16393 + i*21]), tmp_11, tmp_50);
     Goldilocks3::Element tmp_12;
     Goldilocks3::add(tmp_12, (Goldilocks3::Element &)(params.pols[16393 + i*21]), (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_57;
     Goldilocks3::mul(tmp_57, params.pols[44039 + i*17], tmp_12);
     Goldilocks3::Element tmp_13;
     Goldilocks3::add(tmp_13, tmp_50, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_14;
     Goldilocks3::mul(tmp_14, params.pols[44035 + i*17], tmp_13);
     Goldilocks3::Element tmp_15;
     Goldilocks3::mul(tmp_15, params.pols[15 + i*16], tmp_57);
     Goldilocks3::sub((Goldilocks3::Element &)(params.pols[44040 + i*17]), tmp_14, tmp_15);
     Goldilocks3::Element tmp_16;
     Goldilocks3::add(tmp_16, (Goldilocks3::Element &)(params.pols[16393 + i*21]), (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_17;
     Goldilocks3::add(tmp_17, tmp_50, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16396 + i*21]), tmp_16, tmp_17);
     Goldilocks::Element tmp_58;
     Goldilocks::copy(tmp_58, params.pols[7 + i*16]);
     Goldilocks::Element tmp_59;
     Goldilocks::copy(tmp_59, params.pols[7 + i*16]);
     Goldilocks::Element tmp_60;
     Goldilocks::copy(tmp_60, params.pols[9 + i*16]);
     Goldilocks3::Element tmp_18;
     Goldilocks3::mul(tmp_18, tmp_58, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_19;
     Goldilocks3::add(tmp_19, tmp_59, tmp_18);
     Goldilocks3::Element tmp_20;
     Goldilocks3::sub(tmp_20, tmp_19, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_21;
     Goldilocks3::mul(tmp_21, tmp_60, tmp_20);
     Goldilocks3::Element tmp_61;
     Goldilocks3::add(tmp_61, tmp_21, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[44043 + i*17]), tmp_61, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks::Element tmp_62;
     Goldilocks::copy(tmp_62, params.pols[8 + i*16]);
     Goldilocks::Element tmp_63;
     Goldilocks::copy(tmp_63, params.pols[8 + i*16]);
     Goldilocks::Element tmp_64;
     Goldilocks::copy(tmp_64, params.pols[10 + i*16]);
     Goldilocks3::Element tmp_22;
     Goldilocks3::mul(tmp_22, tmp_62, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_23;
     Goldilocks3::add(tmp_23, tmp_63, tmp_22);
     Goldilocks3::Element tmp_24;
     Goldilocks3::sub(tmp_24, tmp_23, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_25;
     Goldilocks3::mul(tmp_25, tmp_64, tmp_24);
     Goldilocks3::Element tmp_65;
     Goldilocks3::add(tmp_65, tmp_25, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[44046 + i*17]), tmp_65, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks::Element tmp_66;
     Goldilocks::copy(tmp_66, params.pols[2 + i*16]);
     Goldilocks3::Element tmp_26;
     Goldilocks3::mul(tmp_26, (Goldilocks::Element &)*params.x_n[i], (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_27;
     Goldilocks3::add(tmp_27, tmp_66, tmp_26);
     Goldilocks3::Element tmp_67;
     Goldilocks3::add(tmp_67, tmp_27, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_68;
     Goldilocks::copy(tmp_68, params.pols[3 + i*16]);
     Goldilocks3::Element tmp_28;
     Goldilocks3::mul(tmp_28, Goldilocks::fromU64(12275445934081160404ULL), (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_29;
     Goldilocks3::mul(tmp_29, (Goldilocks::Element &)*params.x_n[i], tmp_28);
     Goldilocks3::Element tmp_30;
     Goldilocks3::add(tmp_30, tmp_68, tmp_29);
     Goldilocks3::Element tmp_31;
     Goldilocks3::add(tmp_31, tmp_30, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_69;
     Goldilocks3::mul(tmp_69, tmp_67, tmp_31);
     Goldilocks::Element tmp_70;
     Goldilocks::copy(tmp_70, params.pols[4 + i*16]);
     Goldilocks3::Element tmp_32;
     Goldilocks3::mul(tmp_32, Goldilocks::fromU64(4756475762779100925ULL), (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_33;
     Goldilocks3::mul(tmp_33, (Goldilocks::Element &)*params.x_n[i], tmp_32);
     Goldilocks3::Element tmp_34;
     Goldilocks3::add(tmp_34, tmp_70, tmp_33);
     Goldilocks3::Element tmp_35;
     Goldilocks3::add(tmp_35, tmp_34, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16399 + i*21]), tmp_69, tmp_35);
     Goldilocks::Element tmp_71;
     Goldilocks::copy(tmp_71,  params.pConstPols->getElement(3,i));
     Goldilocks3::Element tmp_36;
     Goldilocks3::mul(tmp_36, tmp_71, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_37;
     Goldilocks3::add(tmp_37, tmp_66, tmp_36);
     Goldilocks3::Element tmp_72;
     Goldilocks3::add(tmp_72, tmp_37, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_73;
     Goldilocks::copy(tmp_73,  params.pConstPols->getElement(4,i));
     Goldilocks3::Element tmp_38;
     Goldilocks3::mul(tmp_38, tmp_73, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_39;
     Goldilocks3::add(tmp_39, tmp_68, tmp_38);
     Goldilocks3::Element tmp_40;
     Goldilocks3::add(tmp_40, tmp_39, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_74;
     Goldilocks3::mul(tmp_74, tmp_72, tmp_40);
     Goldilocks::Element tmp_75;
     Goldilocks::copy(tmp_75,  params.pConstPols->getElement(5,i));
     Goldilocks3::Element tmp_41;
     Goldilocks3::mul(tmp_41, tmp_75, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_42;
     Goldilocks3::add(tmp_42, tmp_70, tmp_41);
     Goldilocks3::Element tmp_43;
     Goldilocks3::add(tmp_43, tmp_42, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16402 + i*21]), tmp_74, tmp_43);
}

void AllSteps::step3prev_i(StepsParams &params, uint64_t i) {
     Goldilocks::Element tmp_44;
     Goldilocks::copy(tmp_44,  params.pConstPols->getElement(7,i));
     Goldilocks::Element tmp_45;
     Goldilocks::copy(tmp_45, tmp_44);
     Goldilocks::Element tmp_46;
     Goldilocks::copy(tmp_46,  params.pConstPols->getElement(8,i));
     Goldilocks::Element tmp_47;
     Goldilocks::copy(tmp_47, tmp_46);
     Goldilocks::Element tmp_48;
     Goldilocks::copy(tmp_48, params.pols[14 + i*16]);
     Goldilocks::Element tmp_49;
     Goldilocks::copy(tmp_49, tmp_48);
     Goldilocks::copy(params.pols[44039 + i*17],  params.pConstPols->getElement(6,i));
     Goldilocks3::Element tmp_0;
     Goldilocks3::mul(tmp_0, tmp_45, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_1;
     Goldilocks3::add(tmp_1, tmp_47, tmp_0);
     Goldilocks3::Element tmp_2;
     Goldilocks3::mul(tmp_2, tmp_1, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_3;
     Goldilocks3::add(tmp_3, tmp_49, tmp_2);
     Goldilocks3::Element tmp_4;
     Goldilocks3::sub(tmp_4, tmp_3, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_5;
     Goldilocks3::mul(tmp_5, params.pols[44039 + i*17], tmp_4);
     Goldilocks3::Element tmp_50;
     Goldilocks3::add(tmp_50, tmp_5, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::copy(params.pols[44035 + i*17], params.pols[11 + i*16]);
     Goldilocks::Element tmp_51;
     Goldilocks::copy(tmp_51, params.pols[12 + i*16]);
     Goldilocks::Element tmp_52;
     Goldilocks::copy(tmp_52, tmp_51);
     Goldilocks::Element tmp_53;
     Goldilocks::copy(tmp_53, params.pols[13 + ((i + 1)%1024)*16]);
     Goldilocks::Element tmp_54;
     Goldilocks::copy(tmp_54, tmp_53);
     Goldilocks::Element tmp_55;
     Goldilocks::mul(tmp_55, params.pols[12 + i*16], params.pols[13 + ((i + 1)%1024)*16]);
     Goldilocks::Element tmp_56;
     Goldilocks::copy(tmp_56, tmp_55);
     Goldilocks3::Element tmp_6;
     Goldilocks3::mul(tmp_6, tmp_52, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_7;
     Goldilocks3::add(tmp_7, tmp_54, tmp_6);
     Goldilocks3::Element tmp_8;
     Goldilocks3::mul(tmp_8, tmp_7, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_9;
     Goldilocks3::add(tmp_9, tmp_56, tmp_8);
     Goldilocks3::Element tmp_10;
     Goldilocks3::sub(tmp_10, tmp_9, tmp_50);
     Goldilocks3::Element tmp_11;
     Goldilocks3::mul(tmp_11, params.pols[44035 + i*17], tmp_10);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[16393 + i*21]), tmp_11, tmp_50);
     Goldilocks3::Element tmp_12;
     Goldilocks3::add(tmp_12, (Goldilocks3::Element &)(params.pols[16393 + i*21]), (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_57;
     Goldilocks3::mul(tmp_57, params.pols[44039 + i*17], tmp_12);
     Goldilocks3::Element tmp_13;
     Goldilocks3::add(tmp_13, tmp_50, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_14;
     Goldilocks3::mul(tmp_14, params.pols[44035 + i*17], tmp_13);
     Goldilocks3::Element tmp_15;
     Goldilocks3::mul(tmp_15, params.pols[15 + i*16], tmp_57);
     Goldilocks3::sub((Goldilocks3::Element &)(params.pols[44040 + i*17]), tmp_14, tmp_15);
     Goldilocks3::Element tmp_16;
     Goldilocks3::add(tmp_16, (Goldilocks3::Element &)(params.pols[16393 + i*21]), (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_17;
     Goldilocks3::add(tmp_17, tmp_50, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16396 + i*21]), tmp_16, tmp_17);
     Goldilocks::Element tmp_58;
     Goldilocks::copy(tmp_58, params.pols[7 + i*16]);
     Goldilocks::Element tmp_59;
     Goldilocks::copy(tmp_59, params.pols[7 + i*16]);
     Goldilocks::Element tmp_60;
     Goldilocks::copy(tmp_60, params.pols[9 + i*16]);
     Goldilocks3::Element tmp_18;
     Goldilocks3::mul(tmp_18, tmp_58, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_19;
     Goldilocks3::add(tmp_19, tmp_59, tmp_18);
     Goldilocks3::Element tmp_20;
     Goldilocks3::sub(tmp_20, tmp_19, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_21;
     Goldilocks3::mul(tmp_21, tmp_60, tmp_20);
     Goldilocks3::Element tmp_61;
     Goldilocks3::add(tmp_61, tmp_21, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[44043 + i*17]), tmp_61, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks::Element tmp_62;
     Goldilocks::copy(tmp_62, params.pols[8 + i*16]);
     Goldilocks::Element tmp_63;
     Goldilocks::copy(tmp_63, params.pols[8 + i*16]);
     Goldilocks::Element tmp_64;
     Goldilocks::copy(tmp_64, params.pols[10 + i*16]);
     Goldilocks3::Element tmp_22;
     Goldilocks3::mul(tmp_22, tmp_62, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_23;
     Goldilocks3::add(tmp_23, tmp_63, tmp_22);
     Goldilocks3::Element tmp_24;
     Goldilocks3::sub(tmp_24, tmp_23, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_25;
     Goldilocks3::mul(tmp_25, tmp_64, tmp_24);
     Goldilocks3::Element tmp_65;
     Goldilocks3::add(tmp_65, tmp_25, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[44046 + i*17]), tmp_65, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks::Element tmp_66;
     Goldilocks::copy(tmp_66, params.pols[2 + i*16]);
     Goldilocks3::Element tmp_26;
     Goldilocks3::mul(tmp_26, (Goldilocks::Element &)*params.x_n[i], (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_27;
     Goldilocks3::add(tmp_27, tmp_66, tmp_26);
     Goldilocks3::Element tmp_67;
     Goldilocks3::add(tmp_67, tmp_27, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_68;
     Goldilocks::copy(tmp_68, params.pols[3 + i*16]);
     Goldilocks3::Element tmp_28;
     Goldilocks3::mul(tmp_28, Goldilocks::fromU64(12275445934081160404ULL), (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_29;
     Goldilocks3::mul(tmp_29, (Goldilocks::Element &)*params.x_n[i], tmp_28);
     Goldilocks3::Element tmp_30;
     Goldilocks3::add(tmp_30, tmp_68, tmp_29);
     Goldilocks3::Element tmp_31;
     Goldilocks3::add(tmp_31, tmp_30, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_69;
     Goldilocks3::mul(tmp_69, tmp_67, tmp_31);
     Goldilocks::Element tmp_70;
     Goldilocks::copy(tmp_70, params.pols[4 + i*16]);
     Goldilocks3::Element tmp_32;
     Goldilocks3::mul(tmp_32, Goldilocks::fromU64(4756475762779100925ULL), (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_33;
     Goldilocks3::mul(tmp_33, (Goldilocks::Element &)*params.x_n[i], tmp_32);
     Goldilocks3::Element tmp_34;
     Goldilocks3::add(tmp_34, tmp_70, tmp_33);
     Goldilocks3::Element tmp_35;
     Goldilocks3::add(tmp_35, tmp_34, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16399 + i*21]), tmp_69, tmp_35);
     Goldilocks::Element tmp_71;
     Goldilocks::copy(tmp_71,  params.pConstPols->getElement(3,i));
     Goldilocks3::Element tmp_36;
     Goldilocks3::mul(tmp_36, tmp_71, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_37;
     Goldilocks3::add(tmp_37, tmp_66, tmp_36);
     Goldilocks3::Element tmp_72;
     Goldilocks3::add(tmp_72, tmp_37, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_73;
     Goldilocks::copy(tmp_73,  params.pConstPols->getElement(4,i));
     Goldilocks3::Element tmp_38;
     Goldilocks3::mul(tmp_38, tmp_73, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_39;
     Goldilocks3::add(tmp_39, tmp_68, tmp_38);
     Goldilocks3::Element tmp_40;
     Goldilocks3::add(tmp_40, tmp_39, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_74;
     Goldilocks3::mul(tmp_74, tmp_72, tmp_40);
     Goldilocks::Element tmp_75;
     Goldilocks::copy(tmp_75,  params.pConstPols->getElement(5,i));
     Goldilocks3::Element tmp_41;
     Goldilocks3::mul(tmp_41, tmp_75, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_42;
     Goldilocks3::add(tmp_42, tmp_70, tmp_41);
     Goldilocks3::Element tmp_43;
     Goldilocks3::add(tmp_43, tmp_42, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16402 + i*21]), tmp_74, tmp_43);
}

void AllSteps::step3prev_last(StepsParams &params, uint64_t i) {
     Goldilocks::Element tmp_44;
     Goldilocks::copy(tmp_44,  params.pConstPols->getElement(7,i));
     Goldilocks::Element tmp_45;
     Goldilocks::copy(tmp_45, tmp_44);
     Goldilocks::Element tmp_46;
     Goldilocks::copy(tmp_46,  params.pConstPols->getElement(8,i));
     Goldilocks::Element tmp_47;
     Goldilocks::copy(tmp_47, tmp_46);
     Goldilocks::Element tmp_48;
     Goldilocks::copy(tmp_48, params.pols[14 + i*16]);
     Goldilocks::Element tmp_49;
     Goldilocks::copy(tmp_49, tmp_48);
     Goldilocks::copy(params.pols[44039 + i*17],  params.pConstPols->getElement(6,i));
     Goldilocks3::Element tmp_0;
     Goldilocks3::mul(tmp_0, tmp_45, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_1;
     Goldilocks3::add(tmp_1, tmp_47, tmp_0);
     Goldilocks3::Element tmp_2;
     Goldilocks3::mul(tmp_2, tmp_1, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_3;
     Goldilocks3::add(tmp_3, tmp_49, tmp_2);
     Goldilocks3::Element tmp_4;
     Goldilocks3::sub(tmp_4, tmp_3, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_5;
     Goldilocks3::mul(tmp_5, params.pols[44039 + i*17], tmp_4);
     Goldilocks3::Element tmp_50;
     Goldilocks3::add(tmp_50, tmp_5, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::copy(params.pols[44035 + i*17], params.pols[11 + i*16]);
     Goldilocks::Element tmp_51;
     Goldilocks::copy(tmp_51, params.pols[12 + i*16]);
     Goldilocks::Element tmp_52;
     Goldilocks::copy(tmp_52, tmp_51);
     Goldilocks::Element tmp_53;
     Goldilocks::copy(tmp_53, params.pols[13 + ((i + 1)%1024)*16]);
     Goldilocks::Element tmp_54;
     Goldilocks::copy(tmp_54, tmp_53);
     Goldilocks::Element tmp_55;
     Goldilocks::mul(tmp_55, params.pols[12 + i*16], params.pols[13 + ((i + 1)%1024)*16]);
     Goldilocks::Element tmp_56;
     Goldilocks::copy(tmp_56, tmp_55);
     Goldilocks3::Element tmp_6;
     Goldilocks3::mul(tmp_6, tmp_52, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_7;
     Goldilocks3::add(tmp_7, tmp_54, tmp_6);
     Goldilocks3::Element tmp_8;
     Goldilocks3::mul(tmp_8, tmp_7, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_9;
     Goldilocks3::add(tmp_9, tmp_56, tmp_8);
     Goldilocks3::Element tmp_10;
     Goldilocks3::sub(tmp_10, tmp_9, tmp_50);
     Goldilocks3::Element tmp_11;
     Goldilocks3::mul(tmp_11, params.pols[44035 + i*17], tmp_10);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[16393 + i*21]), tmp_11, tmp_50);
     Goldilocks3::Element tmp_12;
     Goldilocks3::add(tmp_12, (Goldilocks3::Element &)(params.pols[16393 + i*21]), (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_57;
     Goldilocks3::mul(tmp_57, params.pols[44039 + i*17], tmp_12);
     Goldilocks3::Element tmp_13;
     Goldilocks3::add(tmp_13, tmp_50, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_14;
     Goldilocks3::mul(tmp_14, params.pols[44035 + i*17], tmp_13);
     Goldilocks3::Element tmp_15;
     Goldilocks3::mul(tmp_15, params.pols[15 + i*16], tmp_57);
     Goldilocks3::sub((Goldilocks3::Element &)(params.pols[44040 + i*17]), tmp_14, tmp_15);
     Goldilocks3::Element tmp_16;
     Goldilocks3::add(tmp_16, (Goldilocks3::Element &)(params.pols[16393 + i*21]), (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_17;
     Goldilocks3::add(tmp_17, tmp_50, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16396 + i*21]), tmp_16, tmp_17);
     Goldilocks::Element tmp_58;
     Goldilocks::copy(tmp_58, params.pols[7 + i*16]);
     Goldilocks::Element tmp_59;
     Goldilocks::copy(tmp_59, params.pols[7 + i*16]);
     Goldilocks::Element tmp_60;
     Goldilocks::copy(tmp_60, params.pols[9 + i*16]);
     Goldilocks3::Element tmp_18;
     Goldilocks3::mul(tmp_18, tmp_58, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_19;
     Goldilocks3::add(tmp_19, tmp_59, tmp_18);
     Goldilocks3::Element tmp_20;
     Goldilocks3::sub(tmp_20, tmp_19, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_21;
     Goldilocks3::mul(tmp_21, tmp_60, tmp_20);
     Goldilocks3::Element tmp_61;
     Goldilocks3::add(tmp_61, tmp_21, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[44043 + i*17]), tmp_61, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks::Element tmp_62;
     Goldilocks::copy(tmp_62, params.pols[8 + i*16]);
     Goldilocks::Element tmp_63;
     Goldilocks::copy(tmp_63, params.pols[8 + i*16]);
     Goldilocks::Element tmp_64;
     Goldilocks::copy(tmp_64, params.pols[10 + i*16]);
     Goldilocks3::Element tmp_22;
     Goldilocks3::mul(tmp_22, tmp_62, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_23;
     Goldilocks3::add(tmp_23, tmp_63, tmp_22);
     Goldilocks3::Element tmp_24;
     Goldilocks3::sub(tmp_24, tmp_23, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_25;
     Goldilocks3::mul(tmp_25, tmp_64, tmp_24);
     Goldilocks3::Element tmp_65;
     Goldilocks3::add(tmp_65, tmp_25, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[44046 + i*17]), tmp_65, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks::Element tmp_66;
     Goldilocks::copy(tmp_66, params.pols[2 + i*16]);
     Goldilocks3::Element tmp_26;
     Goldilocks3::mul(tmp_26, (Goldilocks::Element &)*params.x_n[i], (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_27;
     Goldilocks3::add(tmp_27, tmp_66, tmp_26);
     Goldilocks3::Element tmp_67;
     Goldilocks3::add(tmp_67, tmp_27, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_68;
     Goldilocks::copy(tmp_68, params.pols[3 + i*16]);
     Goldilocks3::Element tmp_28;
     Goldilocks3::mul(tmp_28, Goldilocks::fromU64(12275445934081160404ULL), (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_29;
     Goldilocks3::mul(tmp_29, (Goldilocks::Element &)*params.x_n[i], tmp_28);
     Goldilocks3::Element tmp_30;
     Goldilocks3::add(tmp_30, tmp_68, tmp_29);
     Goldilocks3::Element tmp_31;
     Goldilocks3::add(tmp_31, tmp_30, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_69;
     Goldilocks3::mul(tmp_69, tmp_67, tmp_31);
     Goldilocks::Element tmp_70;
     Goldilocks::copy(tmp_70, params.pols[4 + i*16]);
     Goldilocks3::Element tmp_32;
     Goldilocks3::mul(tmp_32, Goldilocks::fromU64(4756475762779100925ULL), (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_33;
     Goldilocks3::mul(tmp_33, (Goldilocks::Element &)*params.x_n[i], tmp_32);
     Goldilocks3::Element tmp_34;
     Goldilocks3::add(tmp_34, tmp_70, tmp_33);
     Goldilocks3::Element tmp_35;
     Goldilocks3::add(tmp_35, tmp_34, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16399 + i*21]), tmp_69, tmp_35);
     Goldilocks::Element tmp_71;
     Goldilocks::copy(tmp_71,  params.pConstPols->getElement(3,i));
     Goldilocks3::Element tmp_36;
     Goldilocks3::mul(tmp_36, tmp_71, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_37;
     Goldilocks3::add(tmp_37, tmp_66, tmp_36);
     Goldilocks3::Element tmp_72;
     Goldilocks3::add(tmp_72, tmp_37, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_73;
     Goldilocks::copy(tmp_73,  params.pConstPols->getElement(4,i));
     Goldilocks3::Element tmp_38;
     Goldilocks3::mul(tmp_38, tmp_73, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_39;
     Goldilocks3::add(tmp_39, tmp_68, tmp_38);
     Goldilocks3::Element tmp_40;
     Goldilocks3::add(tmp_40, tmp_39, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_74;
     Goldilocks3::mul(tmp_74, tmp_72, tmp_40);
     Goldilocks::Element tmp_75;
     Goldilocks::copy(tmp_75,  params.pConstPols->getElement(5,i));
     Goldilocks3::Element tmp_41;
     Goldilocks3::mul(tmp_41, tmp_75, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_42;
     Goldilocks3::add(tmp_42, tmp_70, tmp_41);
     Goldilocks3::Element tmp_43;
     Goldilocks3::add(tmp_43, tmp_42, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[16402 + i*21]), tmp_74, tmp_43);
}
